### PR TITLE
[FEATURE] allow developers to save jobs and display saved jobs

### PR DESCRIPTION
**Pull request by rjackson**
This PR introduces the concept of "bookmarks" to the system, or "saved jobs" as they're branded on the frontend.

I've gone _slightly_ off the original specification by allowing any user to bookmark jobs – not just developers. This keeps the overall integration and data model a bit simpler, plus potentially offers more utility than we were anticipating – recruiters might find value in saving jobs, for example.

Jobs are also automatically saved when a user applies for them. If the user previously had that job saved, we only update "applied_at" column against it.

To avoid repeating code across _many_ templates, in this PR I've also lifted some common HTML into two new templates:

- static/views/header-template.html
- static/views/apply-box-developer-template.html

Although I have suffered a bit of duplication when writing the relevant Javascript, but that's only across a few times.

The issue also asked for the saved jobs button to be added to company.html, but this is another one I've skipped. I've added the save button everywhere we show the apply button, but we don't show the apply button on company.html. Every job on that page just links to the relevant job page, which will have the save & apply buttons.

For the "Create a profile popup", I've had to introduce the popup to two new pages: job.html and landing.html. To give it the various variables it needs I've also had to update the various handlers, which then also required me to pass in `*developer.Repository` in many different places. You'll see that a lot in the diffs.

Finally, I've kept the save jobs page itself quite simple. It's a fairly boring table for now. We can adjust this as required.

Still to-do:

- [x] Remove a job from the saved jobs list
- [x] Joining applied jobs via `apply_token` table
- [x] Have a proper review of the changes myself

**Screenshots**

Saved jobs page:

Screenshot 2023-05-03 at 17 10 34

Save job button against a job advert on the landing page:

image

Save job button on a job page:

image

Solves #28 
/claim #28

### CODE REVIEW

**Comment by dm161** [comment]
@rjackson thank you for the PR

- what you did makes sense, can add the ability to remove "saved jobs", but if a job has been applied to, we dont allow them to remove it from the list
- it's fine to join apply_token for now, it would be appropriate to automatically "bookmark" a job if someone applies to it. If you just join the tables we wont have to run any migrations. I can add some index to apply_token if the join gets slow
- let me know when you added the "remove jobs" from bookmark so i will review.

Looks good overall

**Comment by rjackson** [comment]
Alright ready for this to be reviewed @dm161 :)

**Comment by dm161** [comment]
thank you @rjackson looks good - merging now and testing in prod. There is only one thing missing, jobs that have been saved dont show as "saved" when you load the page, I will create an item to track this.

**Comment by dm161** [comment]
https://github.com/golang-cafe/job-board/issues/122

**Pull request merged**
