### PR TITLE
organise head of all pages

### PR DESCRIPTION
**Pull request by dsantos**
Clean up head in preparation for #36. I am not removing anything, just moving around and adding some missing meta elements

### CODE REVIEW

**Comment by dsantos** [comment]
@dm161 What do you think of this?

**Comment by dsantos** [comment]
@dm161 close?

**Comment by dm161** [comment]
Sorry been busy I will check this weekend thank you dsantos

**Comment by dm161** [comment]
@dsantos is close but I have been trying to work on this https://github.com/golang-cafe/job-board/issues/23 first as it's higher priority once this is complete we can refactor the pages splitting HTML

**Pull request closed without merging**
