### PR TITLE
[FEATURE] allow developers to see received messages and profile views

### PR DESCRIPTION
**Pull request by rjackson**
Near enough a mirror image of #125, this change allows developers to see messages they've received.

Scenario | Screenshot
--- | ---
No messages | Screenshot 2023-05-05 at 22 25 13
Many messages | Screenshot 2023-05-05 at 22 24 58
Profile stats | Screenshot 2023-05-06 at 13 12 24
Profile stats (cont) | Screenshot 2023-05-06 at 13 12 31

I've also included some fixes for the bookmarks and sent-messages pages, as I noticed I'd forgotten to update the page meta when creating those pages.

Solves #86 
/claim #86

### CODE REVIEW

**Comment by rjackson** [comment]
Oops, didn't quite read the issue correctly. I'll have a look at the profile views & charts later on.

**Comment by dm161** [comment]
thanks @rjackson -yes there are charrts that can be re-used from edit.html just copy paste the html and probably need a new query to retrieve the timeseries for messages/views

**Comment by rjackson** [comment]
@dm161 Updated with the stats, as described in the original issue!

**Comment by dm161** [comment]
thank you @rjackson - merging -testing in prod

**Pull request merged**
